### ISSUE TITLE
[notice] 단어 목록표 작성 일괄작업

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#46]
- 최소 1차 검토를 완료한 항목에 대해서 사용되는 단어를 집계하여 단어목록표에 적용시킨다.
- root 의 README 파일에 링크가 명시되어있으니 참고할 것
- 수정권한은 @Sumin0916 님께 요청할 것
- 단어 표 추출이 끝난 섹션은 레이블 `단어 목록 추출`을 추가할 것
- 3차 검토완료와 단어표 추출이 끝난 섹션은 해당 섹션 담당자 모두의 동의 하에 클로즈함.

# 단어 목록 추출 리스트

> 이 이슈는 얼마 만큼의 단어 목록이 추출 완료되었는지를 알려준다.

> `Reference`는 포함하지 않는다.

- [X] `introduction`: #2 
- [X] `A Foolish Consistency is the Hobgoblin of Little Minds`: #7
- [X] `code lay-out <indentation>`: #8 
- [X] `code lay-out <tab or spaces?>`: #30 
- [X] `code lay-out <max line length>`: #37
- [x] `code lay-out <나머지>`: #41
- [X] `String Quotes`: #11 
- [X] `Whitespace in Expressions and Statements`: #12 
- [X] `When to use trailing commas`: #16  
- [X] `Comments`: #19 
- [x] `Naming Conventions`: #39 
- [x] `Programming Recommendation`: #42 
- [X] `Copyright`: #40

**Comment by zerosheepmoo** [comment]
# 단어 목록 추출 리스트

> 이 이슈는 얼마 만큼의 단어 목록이 추출 완료되었는지를 알려준다.

> `Reference`는 포함하지 않는다.

- [X] `introduction`: #2 
- [X] `A Foolish Consistency is the Hobgoblin of Little Minds`: #7
- [X] `code lay-out <indentation>`: #8 
- [X] `code lay-out <tab or spaces?>`: #30 
- [X] `code lay-out <max line length>`: #37
- [ ] `code lay-out <나머지>`: #41
- [X] `String Quotes`: #11 
- [X] `Whitespace in Expressions and Statements`: #12 
- [X] `When to use trailing commas`: #16  
- [X] `Comments`: #19 
- [ ] `Naming Conventions`: #39 
- [ ] `Programming Recommendation`: #42 
- [X] `Copyright`: #40

**Comment by zerosheepmoo** [comment]
단어 목록 추출 완료.
추가할 단어가 있으면 해당 섹션 이슈에서 제의바람
