### ISSUE TITLE
[notice] 완료된 번역 섹션

### ISSUE THREAD

**Issue by zerosheepmoo** [zerosheepmoo/pep8-in-korean#48]
# 완료 된 섹션 목록

> 이 이슈는 얼마 만큼의 번역이 완료되었는지를 알려준다.

> `Reference` 는 footnote 기능으로 대체한다.

- [X] `introduction`: #2 
- [x] `A Foolish Consistency is the Hobgoblin of Little Minds`: #7
- [X] `code lay-out <indentation>`: #8 
- [X] `code lay-out <tab or spaces?>`: #30 
- [X] `code lay-out <max line length>`: #37
- [x] `code lay-out <나머지>`: #41
- [x] `String Quotes`: #11 
- [x] `Whitespace in Expressions and Statements`: #12 
- [x] `When to use trailing commas`: #16  
- [x] `Comments`: #19 
- [x] `Naming Conventions`: #39 
- [x] `Programming Recommendation`: #42 
- [x] `Copyright`: #40

**Comment by zerosheepmoo** [comment]
## 프로젝트 완료 예정일

- `~ 5/22`

**Comment by zerosheepmoo** [comment]
프로젝트 완료되었습니다! 모두 고생하셨습니다 :)
